### ISSUE TITLE
sponsor link not working

### ISSUE THREAD

**Issue by brianblain** [jazzto/2019#10]
got all sponsor links working but one is looking like it's been hacked (or could it be at this end?) See screen dump

![Screen Shot 2019-05-29 at 12 46 38 PM](https://user-images.githubusercontent.com/11864078/58575682-9d338e00-8210-11e9-9b4d-946e2448284d.png)

Anna also asks of we could add a little space between logos?

and how do I fix merriam school so the name is hot-linked butthe URL does not show.

**Comment by andrewfn** [comment]
I've increased the spacing (but it will take a couple of hours to get through the caching and be visible.
There is no way I can tell from your screenshot which logo you clicked on.
Which was it?
Thanks

**Comment by brianblain** [comment]
Gyra

**Comment by andrewfn** [comment]
I get:
## This site is under development
and then some random stuff
There is nothing wrong with the link our side, it is their website.

**Comment by andrewfn** [comment]
Try visiting http://gira.ca in your browser.
You will see the same site as we link to. It is not our problem if they can't get gira.ca working.

**Comment by andrewfn** [comment]
Ah, I see the problem
They have misconfigured their website to reject gira.ca unless it has www in front of it.
I have fixed the link, but somebody should tell them!
