### ISSUE TITLE
photo page

### ISSUE THREAD

**Issue by brianblain** [jazzto/2019#11]
well, it looks like we're underway again! I think you have to make the update on the photo page.  I've created a new Flickr group - 2019 TD Toronto Jazz Festival

it's at: https://www.flickr.com/groups/14612697@N20/

can you remove the thank-you message and link to the new group

will you be making it down to Yorkville for some shows?

**Comment by andrewfn** [comment]
Done.
You might have to flush your cache to see the new page,
or simply look at the raw gallery here: http://torontojazz.com/flickrslidr/flickr.html
