### ISSUE TITLE
post festival home page

### ISSUE THREAD

**Issue by brianblain** [jazzto/2019#12]
hi Andrew - I guess we got through another year without a crash.  Thanks to you.  Hope you got to hear a little jazz.  Here is an image from Anna to put up on the post festival home page (I think it was above the slide show)
![Thank you!](https://user-images.githubusercontent.com/11864078/60403600-62a17600-9b6d-11e9-8f20-74c719af3d12.png)

**Comment by andrewfn** [comment]
We got to see Diana Ross who is such a good entertainer!
I'll get the photo us for you shortly.

**Comment by andrewfn** [comment]
Photo on the home page now.

**Comment by brianblain** [comment]
thank you image is not displaying on my iPhone - slide show is there

**Comment by andrewfn** [comment]
Yes, for some reason it is not showing on the mobile site.
I'm looking into it.
