### ISSUE TITLE
Possible to duplicate pages?

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2019#16]
Hey Andrew - is it possible to duplicate pages?  As we add pages to our Stories From Home initiative, it would be much easier to preserve formatting if we could just duplicate the previous page...

Let me know - thanks!

**Comment by andrewfn** [comment]
Yes, there is an add-on widget for exactly that purpose.
I have installed it, and you should now soo a "Clone Content" link near the
top of any page you can edit.
Note that the cloning does not take effect until you actually save the
page, so you can cancel out of it.
Note also that it changes the title so you can be sure if you are editing
the original page or the cloned on.
I use it all the time on other sites and it works great.

Let me know if you have any questions
Andrew

**Comment by joshgrossman** [comment]
Brilliant - thanks!  I see it, and will test it out...

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27

TD Toronto Jazz Festival Ranked #1 Music Event in Canada in 2019 (BizBash)
