### ISSUE TITLE
Printable calendar

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2019#4]
@brianblain 
Please let me know when things are ready for me to create the printable calendar.
- The shows have to be published for me to do this, so I am guessing it is as soon as they are announced on Tuesday morning.
- I need to know which venues are to be in the top section (featured)

**Comment by andrewfn** [comment]
Not heard back from you on this.
I imagine it is getting urgent that we have a printable calendar.

**Comment by brianblain** [comment]
can we just have the same priority as the at-a-glance - big shows at the top.  Also I saw a note from last year about trying to repeat the header w/dates on each page but I think you said that would require some re-engineering

**Comment by andrewfn** [comment]
I was able to repeat the header w/dates on every page.
Printable calendar done now, with a link on the calendar page to the printable version.
Let me know if any issues.
